/*
 * DSH 娓呮柊鍙埍涓婚鍊欓€?路 璋冭壊鏉垮畾涔夛紙v2锛? * ---------------------------------------
 * 涓€涓富棰?= ThemeDefinition { id, colorScheme, tokens }銆? * tokens 瑕嗙洊 --dsw-alias-* / --dsw-specific-* 璇箟灞傦紝澶栧姞鎺掔増銆侀槾褰便€? * 鎬濊€冨潡娓愬彉杩欎簺"涓嶅甫 alias- 鍓嶇紑浣嗗悓鏍锋槸涓婚 token"鐨勫彉閲忋€? *
 * 涓夋潯璁捐绾緥锛? *   1. 鍙崲鑹茬浉锛屼笉鏀瑰叧绯伙細灞傜骇宸€佸姣斿叧绯荤収鎶勫涓荤粨鏋勩€? *   2. 浜壊涓嬭緭鍏ユ琛ㄩ潰涓嶈姣旂焊鏇存殫锛堝惁鍒欒璧锋潵鍍忕鐢級銆? *   3. 闃村奖鐢ㄤ富棰樿嚜宸辩殑澧ㄨ壊锛屼笉鐢ㄤ腑鎬х函榛戙€? *
 * 涓ゆ潯浠庡涓诲疄娴嬪緱鍒扮殑纭害鏉燂紙v1 鏇捐俯锛夛細
 *   路 --dsw-alias-brand-primary 鏄?*楂樺姣斿ⅷ鑹?*锛屼笉鏄搧鐗屽己璋冭壊銆? *     瀹夸富浜壊缁欑殑鏄繎榛?#0f1115銆佹殫鑹茬粰鐨勬槸杩戠櫧 #f9fafb锛涘畠琚寜閽枃瀛? *     鍜屾爣棰樻秷璐广€傚搧鐗屽己璋冭壊璧?--dsw-alias-button-info-fill銆? *   路 --dsw-alias-label-caption 瀹夸富鑷繁鍙湁 1.92:1锛堝急鍖栧厓鏁版嵁锛屼綆浜?AA锛夛紝
 *     鎵€浠ュ畠鏄?淇濇寔瀹夸富姘村钩"鑰屼笉鏄?蹇呴』杩?3:1"銆? */

/** 鍙栦竴浠?token 楠ㄦ灦锛屽噺灏戜笁濂椾富棰樹箣闂寸殑閲嶅涔﹀啓銆?*/
function base() {
  return {
    // 鑳屾櫙灞傜骇
    '--dsw-alias-bg-base': '', '--dsw-alias-bg-layer-1': '', '--dsw-alias-bg-layer-2': '',
    '--dsw-alias-bg-layer-3': '', '--dsw-alias-bg-overlay': '', '--dsw-alias-bg-module-platform': '',
    '--dsw-alias-bg-multi-select': '', '--dsw-alias-bg-skeleton': '',
    // 閬僵
    '--dsw-alias-bg-mask-1': '', '--dsw-alias-bg-mask-2': '', '--dsw-alias-bg-mask-3': '',
    // 杈规
    '--dsw-alias-border-l1': '', '--dsw-alias-border-l2': '', '--dsw-alias-border-l3': '',
    '--dsw-alias-border-l4': '', '--dsw-alias-border-inverted': '',
    // 鏂囧瓧
    '--dsw-alias-label-primary': '', '--dsw-alias-label-secondary': '', '--dsw-alias-label-tertiary': '',
    '--dsw-alias-label-caption': '', '--dsw-alias-label-dimmed': '', '--dsw-alias-label-primary-dimmed': '',
    '--dsw-alias-label-primary-foreground': '', '--dsw-alias-label-primary-inverted': '',
    '--dsw-alias-label-primary-bluish': '',
    // 鍝佺墝涓庣姸鎬?    '--dsw-alias-brand-primary': '', '--dsw-alias-brand-primary-invert': '', '--dsw-alias-brand-text': '',
    '--dsw-alias-state-business-primary': '', '--dsw-alias-state-business-tertiary': '',
    '--dsw-alias-state-success-primary': '', '--dsw-alias-state-success-secondary': '',
    '--dsw-alias-state-success-tertiary': '', '--dsw-alias-state-warn-primary': '',
    '--dsw-alias-state-warn-secondary': '', '--dsw-alias-state-warn-tertiary': '',
    '--dsw-alias-state-error-primary': '', '--dsw-alias-state-error-secondary': '',
    // 浜や簰
    '--dsw-alias-interactive-bg-hover': '', '--dsw-alias-interactive-bg-hover-solid': '',
    '--dsw-alias-interactive-bg-active': '', '--dsw-alias-interactive-bg-hover-accent': '',
    '--dsw-alias-interactive-bg-hover-danger': '',
    // 鎸夐挳
    '--dsw-alias-button-primary-fill': '', '--dsw-alias-button-primary-hover': '',
    '--dsw-alias-button-primary-dimmed': '', '--dsw-alias-button-info-fill': '',
    '--dsw-alias-button-info-hover': '', '--dsw-alias-button-elevated-fill': '',
    '--dsw-alias-button-floating-fill': '', '--dsw-alias-button-floating-hover': '',
    '--dsw-alias-button-contrast-fill': '', '--dsw-alias-button-ghost-active-fill': '',
    '--dsw-alias-button-ghost-active-border': '', '--dsw-alias-button-ghost-active-hover': '',
    // Markdown / 浠ｇ爜
    '--dsw-alias-markdown-code-block': '', '--dsw-alias-markdown-code-block-banner': '',
    '--dsw-alias-markdown-inline-code': '', '--dsw-alias-markdown-tag': '',
    '--dsw-alias-markdown-citation': '', '--dsw-alias-markdown-placeholder': '',
    '--dsw-alias-markdown-code-segment-selected': '', '--dsw-alias-markdown-code-segment-unselected': '',
    // 婊氬姩鏉?    '--dsw-alias-scrollbar-bg-l1': '', '--dsw-alias-scrollbar-bg-l2': '',
    '--dsw-alias-scrollbar-hover-l1': '', '--dsw-alias-scrollbar-hover-l2': '',
    // 娴眰
    '--dsw-alias-tooltip-bg': '', '--dsw-alias-toast-bg': '',
    // 鐗瑰寲琛ㄩ潰
    '--dsw-specific-bubble': '', '--dsw-specific-bubble-highlight': '', '--dsw-specific-input-major': '',
    '--dsw-specific-login-input': '', '--dsw-specific-menu': '', '--dsw-specific-selector': '',
    '--dsw-specific-sidebar-fill': '', '--dsw-specific-sidebar-nav-item-hover': '',
    '--dsw-specific-sidebar-nav-item-active': '', '--dsw-specific-sidebar-nav-item-active-accent': '',
    '--dsw-specific-tip': '',
  }
}

function build(spec) {
  const tokens = base()
  for (const [k, v] of Object.entries(spec)) if (v !== undefined && v !== '') tokens[k] = v
  return tokens
}

/* 鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲
   鍊欓€?1 路 钖勮嵎姹芥按锛圡int Soda锛?   娓呴€忚杽鑽风豢 + 鏌犳濂舵补 + 鑽夎帗鐐圭紑銆傚儚涓€鏀垰寮€鐨勮嫃鎵撴按銆?   鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲 */

export const mintSodaLight = {
  id: 'mint-soda-light',
  colorScheme: 'light',
  family: '钖勮嵎姹芥按',
  accent: '#2fb99a',
  accentAlt: '#eaa63c',
  anchorHex: '#7fd8c0',
  tokens: build({
    '--dsw-alias-bg-base': '#f7fbf9',
    '--dsw-alias-bg-layer-1': '#ffffff',
    '--dsw-alias-bg-layer-2': '#ffffff',
    '--dsw-alias-bg-layer-3': '#f4faf7',
    '--dsw-alias-bg-overlay': '#eaf5f0',
    '--dsw-alias-bg-module-platform': '#eff7f3',
    '--dsw-alias-bg-multi-select': '#eaf5f0',
    '--dsw-alias-bg-skeleton': '#0f2f2a0a',
    '--dsw-alias-bg-mask-1': '#123a3333',
    '--dsw-alias-bg-mask-2': '#123a331a',
    '--dsw-alias-bg-mask-3': '#123a3366',
    '--dsw-alias-border-l1': '#123a330d',
    '--dsw-alias-border-l2': '#123a331a',
    '--dsw-alias-border-l3': '#123a3324',
    '--dsw-alias-border-l4': '#123a3333',
    '--dsw-alias-border-inverted': '#ffffff1f',
    '--dsw-alias-label-primary': '#17352e',
    '--dsw-alias-label-secondary': '#4b6b63',
    '--dsw-alias-label-tertiary': '#5d7d75',
    '--dsw-alias-label-caption': '#7b978f',
    '--dsw-alias-label-dimmed': '#c3d8d2',
    '--dsw-alias-label-primary-dimmed': '#22493f',
    '--dsw-alias-label-primary-foreground': '#ffffff',
    '--dsw-alias-label-primary-inverted': '#ffffff',
    '--dsw-alias-label-primary-bluish': '#17352e',
    // 品牌墨色（高对比，被按钮文字/标题消费）
    '--dsw-alias-brand-primary': '#17352e',
    '--dsw-alias-brand-primary-invert': '#17352e',
    '--dsw-alias-brand-text': '#17352e',
    '--dsw-alias-state-business-primary': '#2f9ec2',
    '--dsw-alias-state-business-tertiary': '#e2f5fa',
    '--dsw-alias-state-success-primary': '#2f9e6a',
    '--dsw-alias-state-success-secondary': '#6fd3a4',
    '--dsw-alias-state-success-tertiary': '#e6f8ee',
    '--dsw-alias-state-warn-primary': '#b97b1c',
    '--dsw-alias-state-warn-secondary': '#eaa63c',
    '--dsw-alias-state-warn-tertiary': '#fdf3e2',
    '--dsw-alias-state-error-primary': '#d24b46',
    '--dsw-alias-state-error-secondary': '#f0736f',
    '--dsw-alias-interactive-bg-hover': '#2fb99a14',
    '--dsw-alias-interactive-bg-hover-solid': '#eaf7f3',
    '--dsw-alias-interactive-bg-active': '#2fb99a24',
    '--dsw-alias-interactive-bg-hover-accent': '#2fb99a24',
    '--dsw-alias-interactive-bg-hover-danger': '#f0736f14',
    // 鍝佺墝寮鸿皟鑹茶蛋鎸夐挳濉厖
    '--dsw-alias-button-primary-fill': '#2fb99a',
    '--dsw-alias-button-primary-hover': '#28a98c',
    '--dsw-alias-button-primary-dimmed': '#cdeee5',
    '--dsw-alias-button-info-fill': '#2f9ec2',
    '--dsw-alias-button-info-hover': '#2b8cac',
    '--dsw-alias-button-elevated-fill': '#ffffff',
    '--dsw-alias-button-floating-fill': '#ffffff',
    '--dsw-alias-button-floating-hover': '#f4faf7',
    '--dsw-alias-button-contrast-fill': '#17352e',
    '--dsw-alias-button-ghost-active-fill': '#e6f3ef',
    '--dsw-alias-button-ghost-active-border': '#7b978f',
    '--dsw-alias-button-ghost-active-hover': '#dbece7',
    '--dsw-alias-markdown-code-block': '#f0f8f5',
    '--dsw-alias-markdown-code-block-banner': '#e7f3ef',
    '--dsw-alias-markdown-inline-code': '#e8f5f1',
    '--dsw-alias-markdown-tag': '#e8f5f1',
    '--dsw-alias-markdown-citation': '#e8f5f1',
    '--dsw-alias-markdown-placeholder': '#f4faf7',
    '--dsw-alias-markdown-code-segment-selected': '#ffffff',
    '--dsw-alias-markdown-code-segment-unselected': '#f4faf7',
    '--dsw-alias-scrollbar-bg-l1': '#c3d8d2',
    '--dsw-alias-scrollbar-bg-l2': '#b3cec7',
    '--dsw-alias-scrollbar-hover-l1': '#9dbcb4',
    '--dsw-alias-scrollbar-hover-l2': '#9dbcb4',
    '--dsw-alias-tooltip-bg': '#17352e',
    '--dsw-alias-toast-bg': '#22493f',
    '--dsw-specific-bubble': '#eaf7f3',
    '--dsw-specific-bubble-highlight': '#ffffff',
    '--dsw-specific-input-major': '#ffffff',
    '--dsw-specific-login-input': '#ffffff',
    '--dsw-specific-menu': '#ffffff',
    '--dsw-specific-selector': '#eef7f4',
    '--dsw-specific-sidebar-fill': '#eaf5f0',
    '--dsw-specific-sidebar-nav-item-hover': '#2fb99a14',
    '--dsw-specific-sidebar-nav-item-active': '#d9f0e9',
    '--dsw-specific-sidebar-nav-item-active-accent': '#2fb99a',
    '--dsw-specific-tip': '#e8f5f1',
  }),
}

export const mintSodaDark = {
  id: 'mint-soda-dark',
  colorScheme: 'dark',
  family: '钖勮嵎姹芥按',
  accent: '#5fe0c0',
  accentAlt: '#f0c168',
  anchorHex: '#5fe0c0',
  tokens: build({
    '--dsw-alias-bg-base': '#0d1f1c',
    '--dsw-alias-bg-layer-1': '#132926',
    '--dsw-alias-bg-layer-2': '#183430',
    '--dsw-alias-bg-layer-3': '#1e3f3a',
    '--dsw-alias-bg-overlay': '#22493f',
    '--dsw-alias-bg-module-platform': '#183430',
    '--dsw-alias-bg-multi-select': '#1e3f3a',
    '--dsw-alias-bg-skeleton': '#ffffff14',
    '--dsw-alias-bg-mask-1': '#00000080',
    '--dsw-alias-bg-mask-2': '#00000033',
    '--dsw-alias-bg-mask-3': '#0000007a',
    '--dsw-alias-border-l1': '#8fe6d01f',
    '--dsw-alias-border-l2': '#8fe6d02e',
    '--dsw-alias-border-l3': '#8fe6d042',
    '--dsw-alias-border-l4': '#8fe6d05c',
    '--dsw-alias-border-inverted': '#ffffff14',
    '--dsw-alias-label-primary': '#e6f7f2',
    '--dsw-alias-label-secondary': '#a8c9c2',
    '--dsw-alias-label-tertiary': '#8fb3ac',
    '--dsw-alias-label-caption': '#7a9d96',
    '--dsw-alias-label-dimmed': '#3d5b55',
    '--dsw-alias-label-primary-dimmed': '#cbe8e1',
    '--dsw-alias-label-primary-foreground': '#0d1f1c',
    '--dsw-alias-label-primary-inverted': '#132926',
    '--dsw-alias-label-primary-bluish': '#e6f7f2',
    '--dsw-alias-brand-primary': '#e6f7f2',
    '--dsw-alias-brand-primary-invert': '#e6f7f2',
    '--dsw-alias-brand-text': '#e6f7f2',
    '--dsw-alias-state-business-primary': '#63d7ef',
    '--dsw-alias-state-business-tertiary': '#143a42',
    '--dsw-alias-state-success-primary': '#5fd79c',
    '--dsw-alias-state-success-secondary': '#8ee8b8',
    '--dsw-alias-state-success-tertiary': '#123a2a',
    '--dsw-alias-state-warn-primary': '#f0c168',
    '--dsw-alias-state-warn-secondary': '#f7d894',
    '--dsw-alias-state-warn-tertiary': '#3b2f16',
    '--dsw-alias-state-error-primary': '#f78f8a',
    '--dsw-alias-state-error-secondary': '#ffb3af',
    '--dsw-alias-interactive-bg-hover': '#5fe0c01f',
    '--dsw-alias-interactive-bg-hover-solid': '#1e3f3a',
    '--dsw-alias-interactive-bg-active': '#5fe0c033',
    '--dsw-alias-interactive-bg-hover-accent': '#5fe0c03d',
    '--dsw-alias-interactive-bg-hover-danger': '#f78f8a26',
    '--dsw-alias-button-primary-fill': '#5fe0c0',
    '--dsw-alias-button-primary-hover': '#7ae9cd',
    '--dsw-alias-button-primary-dimmed': '#25544c',
    '--dsw-alias-button-info-fill': '#63d7ef',
    '--dsw-alias-button-info-hover': '#8ae3f5',
    '--dsw-alias-button-elevated-fill': '#1e3f3a',
    '--dsw-alias-button-floating-fill': '#183430',
    '--dsw-alias-button-floating-hover': '#1e3f3a',
    '--dsw-alias-button-contrast-fill': '#e6f7f2',
    '--dsw-alias-button-ghost-active-fill': '#1e3f3a',
    '--dsw-alias-button-ghost-active-border': '#4d7a72',
    '--dsw-alias-button-ghost-active-hover': '#25544c',
    '--dsw-alias-markdown-code-block': '#0f2622',
    '--dsw-alias-markdown-code-block-banner': '#183430',
    '--dsw-alias-markdown-inline-code': '#1e3f3a',
    '--dsw-alias-markdown-tag': '#1e3f3a',
    '--dsw-alias-markdown-citation': '#1e3f3a',
    '--dsw-alias-markdown-placeholder': '#183430',
    '--dsw-alias-markdown-code-segment-selected': '#1e3f3a',
    '--dsw-alias-markdown-code-segment-unselected': '#0f2622',
    '--dsw-alias-scrollbar-bg-l1': '#2c4a44',
    '--dsw-alias-scrollbar-bg-l2': '#3a5d56',
    '--dsw-alias-scrollbar-hover-l1': '#456e66',
    '--dsw-alias-scrollbar-hover-l2': '#456e66',
    '--dsw-alias-tooltip-bg': '#22493f',
    '--dsw-alias-toast-bg': '#25544c',
    '--dsw-specific-bubble': '#1e3f3a',
    '--dsw-specific-bubble-highlight': '#183430',
    '--dsw-specific-input-major': '#183430',
    '--dsw-specific-login-input': '#183430',
    '--dsw-specific-menu': '#1e3f3a',
    '--dsw-specific-selector': '#183430',
    '--dsw-specific-sidebar-fill': '#122925',
    '--dsw-specific-sidebar-nav-item-hover': '#5fe0c01f',
    '--dsw-specific-sidebar-nav-item-active': '#1e3f3a',
    '--dsw-specific-sidebar-nav-item-active-accent': '#5fe0c0',
    '--dsw-specific-tip': '#1e3f3a',
  }),
}

/* 鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲
   鍊欓€?2 路 妯辫姳楹昏柉锛圫akura Mochi锛?   妯辩矇 + 濂舵补鐧?+ 鎶硅尪鐐圭紑銆傝蒋绯紝甯︿竴鐐硅叜绾㈡劅銆?   鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲 */

export const sakuraMochiLight = {
  id: 'sakura-mochi-light',
  colorScheme: 'light',
  family: '妯辫姳楹昏柉',
  accent: '#ef7d9a',
  accentAlt: '#5fb98a',
  anchorHex: '#f7a8b8',
  tokens: build({
    '--dsw-alias-bg-base': '#fff9fa',
    '--dsw-alias-bg-layer-1': '#ffffff',
    '--dsw-alias-bg-layer-2': '#ffffff',
    '--dsw-alias-bg-layer-3': '#fff6f8',
    '--dsw-alias-bg-overlay': '#ffeaee',
    '--dsw-alias-bg-module-platform': '#fff5f7',
    '--dsw-alias-bg-multi-select': '#ffeaee',
    '--dsw-alias-bg-skeleton': '#4a243010',
    '--dsw-alias-bg-mask-1': '#4a243033',
    '--dsw-alias-bg-mask-2': '#4a24301a',
    '--dsw-alias-bg-mask-3': '#4a243066',
    '--dsw-alias-border-l1': '#4a24300f',
    '--dsw-alias-border-l2': '#4a24301f',
    '--dsw-alias-border-l3': '#4a243029',
    '--dsw-alias-border-l4': '#4a24303d',
    '--dsw-alias-border-inverted': '#ffffff1f',
    '--dsw-alias-label-primary': '#3b2830',
    '--dsw-alias-label-secondary': '#6f5460',
    '--dsw-alias-label-tertiary': '#846773',
    '--dsw-alias-label-caption': '#9b7f8b',
    '--dsw-alias-label-dimmed': '#dcc6ce',
    '--dsw-alias-label-primary-dimmed': '#4d333d',
    '--dsw-alias-label-primary-foreground': '#ffffff',
    '--dsw-alias-label-primary-inverted': '#ffffff',
    '--dsw-alias-label-primary-bluish': '#3b2830',
    '--dsw-alias-brand-primary': '#3b2830',
    '--dsw-alias-brand-primary-invert': '#3b2830',
    '--dsw-alias-brand-text': '#3b2830',
    '--dsw-alias-state-business-primary': '#5f8fd8',
    '--dsw-alias-state-business-tertiary': '#eef3fd',
    '--dsw-alias-state-success-primary': '#4a9e74',
    '--dsw-alias-state-success-secondary': '#8bd0ab',
    '--dsw-alias-state-success-tertiary': '#eaf7f0',
    '--dsw-alias-state-warn-primary': '#b8802f',
    '--dsw-alias-state-warn-secondary': '#e0a24e',
    '--dsw-alias-state-warn-tertiary': '#fdf4e6',
    '--dsw-alias-state-error-primary': '#d24b5b',
    '--dsw-alias-state-error-secondary': '#e8656f',
    '--dsw-alias-interactive-bg-hover': '#ef7d9a14',
    '--dsw-alias-interactive-bg-hover-solid': '#fff0f3',
    '--dsw-alias-interactive-bg-active': '#ef7d9a26',
    '--dsw-alias-interactive-bg-hover-accent': '#ef7d9a26',
    '--dsw-alias-interactive-bg-hover-danger': '#e8656f14',
    '--dsw-alias-button-primary-fill': '#ef7d9a',
    '--dsw-alias-button-primary-hover': '#e46b8a',
    '--dsw-alias-button-primary-dimmed': '#ffd9e2',
    '--dsw-alias-button-info-fill': '#5f8fd8',
    '--dsw-alias-button-info-hover': '#507fc9',
    '--dsw-alias-button-elevated-fill': '#ffffff',
    '--dsw-alias-button-floating-fill': '#ffffff',
    '--dsw-alias-button-floating-hover': '#fff6f8',
    '--dsw-alias-button-contrast-fill': '#3b2830',
    '--dsw-alias-button-ghost-active-fill': '#ffeaee',
    '--dsw-alias-button-ghost-active-border': '#9b7f8b',
    '--dsw-alias-button-ghost-active-hover': '#ffdfe5',
    '--dsw-alias-markdown-code-block': '#fff3f5',
    '--dsw-alias-markdown-code-block-banner': '#ffe9ed',
    '--dsw-alias-markdown-inline-code': '#ffeef1',
    '--dsw-alias-markdown-tag': '#ffeef1',
    '--dsw-alias-markdown-citation': '#ffeef1',
    '--dsw-alias-markdown-placeholder': '#fff6f8',
    '--dsw-alias-markdown-code-segment-selected': '#ffffff',
    '--dsw-alias-markdown-code-segment-unselected': '#fff6f8',
    '--dsw-alias-scrollbar-bg-l1': '#e8cdd5',
    '--dsw-alias-scrollbar-bg-l2': '#dfc0c9',
    '--dsw-alias-scrollbar-hover-l1': '#cfa8b4',
    '--dsw-alias-scrollbar-hover-l2': '#cfa8b4',
    '--dsw-alias-tooltip-bg': '#3b2830',
    '--dsw-alias-toast-bg': '#4d333d',
    '--dsw-specific-bubble': '#ffeef1',
    '--dsw-specific-bubble-highlight': '#ffffff',
    '--dsw-specific-input-major': '#ffffff',
    '--dsw-specific-login-input': '#ffffff',
    '--dsw-specific-menu': '#ffffff',
    '--dsw-specific-selector': '#fff5f7',
    '--dsw-specific-sidebar-fill': '#fff0f3',
    '--dsw-specific-sidebar-nav-item-hover': '#ef7d9a14',
    '--dsw-specific-sidebar-nav-item-active': '#ffdfe6',
    '--dsw-specific-sidebar-nav-item-active-accent': '#ef7d9a',
    '--dsw-specific-tip': '#ffeef1',
  }),
}

export const sakuraMochiDark = {
  id: 'sakura-mochi-dark',
  colorScheme: 'dark',
  family: '妯辫姳楹昏柉',
  accent: '#f7a8b8',
  accentAlt: '#8ed6ae',
  anchorHex: '#f7a8b8',
  tokens: build({
    '--dsw-alias-bg-base': '#211920',
    '--dsw-alias-bg-layer-1': '#2b2029',
    '--dsw-alias-bg-layer-2': '#352731',
    '--dsw-alias-bg-layer-3': '#3f2e39',
    '--dsw-alias-bg-overlay': '#4a3644',
    '--dsw-alias-bg-module-platform': '#352731',
    '--dsw-alias-bg-multi-select': '#3f2e39',
    '--dsw-alias-bg-skeleton': '#ffffff14',
    '--dsw-alias-bg-mask-1': '#00000080',
    '--dsw-alias-bg-mask-2': '#00000033',
    '--dsw-alias-bg-mask-3': '#0000007a',
    '--dsw-alias-border-l1': '#ffc8d81f',
    '--dsw-alias-border-l2': '#ffc8d82e',
    '--dsw-alias-border-l3': '#ffc8d842',
    '--dsw-alias-border-l4': '#ffc8d85c',
    '--dsw-alias-border-inverted': '#ffffff14',
    '--dsw-alias-label-primary': '#ffeef3',
    '--dsw-alias-label-secondary': '#d4b3c0',
    '--dsw-alias-label-tertiary': '#bb9aa8',
    '--dsw-alias-label-caption': '#a48795',
    '--dsw-alias-label-dimmed': '#5b4250',
    '--dsw-alias-label-primary-dimmed': '#f5d8e2',
    '--dsw-alias-label-primary-foreground': '#211920',
    '--dsw-alias-label-primary-inverted': '#2b2029',
    '--dsw-alias-label-primary-bluish': '#ffeef3',
    '--dsw-alias-brand-primary': '#ffeef3',
    '--dsw-alias-brand-primary-invert': '#ffeef3',
    '--dsw-alias-brand-text': '#ffeef3',
    '--dsw-alias-state-business-primary': '#a8c4f0',
    '--dsw-alias-state-business-tertiary': '#2a3446',
    '--dsw-alias-state-success-primary': '#8ed6ae',
    '--dsw-alias-state-success-secondary': '#b0e6c8',
    '--dsw-alias-state-success-tertiary': '#1f3a2c',
    '--dsw-alias-state-warn-primary': '#f0c884',
    '--dsw-alias-state-warn-secondary': '#f7dba8',
    '--dsw-alias-state-warn-tertiary': '#3d3118',
    '--dsw-alias-state-error-primary': '#f78f9b',
    '--dsw-alias-state-error-secondary': '#ffb3bc',
    '--dsw-alias-interactive-bg-hover': '#f7a8b81f',
    '--dsw-alias-interactive-bg-hover-solid': '#3f2e39',
    '--dsw-alias-interactive-bg-active': '#f7a8b833',
    '--dsw-alias-interactive-bg-hover-accent': '#f7a8b83d',
    '--dsw-alias-interactive-bg-hover-danger': '#f78f9b26',
    '--dsw-alias-button-primary-fill': '#f7a8b8',
    '--dsw-alias-button-primary-hover': '#ffc0cd',
    '--dsw-alias-button-primary-dimmed': '#5c3a47',
    '--dsw-alias-button-info-fill': '#a8c4f0',
    '--dsw-alias-button-info-hover': '#c0d5f7',
    '--dsw-alias-button-elevated-fill': '#3f2e39',
    '--dsw-alias-button-floating-fill': '#352731',
    '--dsw-alias-button-floating-hover': '#3f2e39',
    '--dsw-alias-button-contrast-fill': '#ffeef3',
    '--dsw-alias-button-ghost-active-fill': '#3f2e39',
    '--dsw-alias-button-ghost-active-border': '#8a6a78',
    '--dsw-alias-button-ghost-active-hover': '#5c3a47',
    '--dsw-alias-markdown-code-block': '#241b22',
    '--dsw-alias-markdown-code-block-banner': '#352731',
    '--dsw-alias-markdown-inline-code': '#3f2e39',
    '--dsw-alias-markdown-tag': '#3f2e39',
    '--dsw-alias-markdown-citation': '#3f2e39',
    '--dsw-alias-markdown-placeholder': '#352731',
    '--dsw-alias-markdown-code-segment-selected': '#3f2e39',
    '--dsw-alias-markdown-code-segment-unselected': '#241b22',
    '--dsw-alias-scrollbar-bg-l1': '#4a3644',
    '--dsw-alias-scrollbar-bg-l2': '#5b4250',
    '--dsw-alias-scrollbar-hover-l1': '#6d4f5e',
    '--dsw-alias-scrollbar-hover-l2': '#6d4f5e',
    '--dsw-alias-tooltip-bg': '#4a3644',
    '--dsw-alias-toast-bg': '#5c3a47',
    '--dsw-specific-bubble': '#3f2e39',
    '--dsw-specific-bubble-highlight': '#352731',
    '--dsw-specific-input-major': '#352731',
    '--dsw-specific-login-input': '#352731',
    '--dsw-specific-menu': '#3f2e39',
    '--dsw-specific-selector': '#352731',
    '--dsw-specific-sidebar-fill': '#1d151b',
    '--dsw-specific-sidebar-nav-item-hover': '#f7a8b81f',
    '--dsw-specific-sidebar-nav-item-active': '#3f2e39',
    '--dsw-specific-sidebar-nav-item-active-accent': '#f7a8b8',
    '--dsw-specific-tip': '#3f2e39',
  }),
}

/* 鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲
   鍊欓€?3 路 鏌犳濂舵补锛圠emon Cream锛?   濂舵补榛?+ 铚傝湝 + 澶╄摑鐐圭紑銆傛殩涔庝箮锛屽儚涓嬪崍涓夌偣鐨勮泲绯曘€?   鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲鈺愨晲 */

export const lemonCreamLight = {
  id: 'lemon-cream-light',
  colorScheme: 'light',
  family: '鏌犳濂舵补',
  accent: '#e8a92a',
  accentAlt: '#4fa8d8',
  anchorHex: '#f7c948',
  tokens: build({
    '--dsw-alias-bg-base': '#fffcf3',
    '--dsw-alias-bg-layer-1': '#ffffff',
    '--dsw-alias-bg-layer-2': '#ffffff',
    '--dsw-alias-bg-layer-3': '#fdf9ee',
    '--dsw-alias-bg-overlay': '#fbf0d8',
    '--dsw-alias-bg-module-platform': '#fdf8ec',
    '--dsw-alias-bg-multi-select': '#fbf0d8',
    '--dsw-alias-bg-skeleton': '#3a2e0f0a',
    '--dsw-alias-bg-mask-1': '#3a2e0f33',
    '--dsw-alias-bg-mask-2': '#3a2e0f1a',
    '--dsw-alias-bg-mask-3': '#3a2e0f66',
    '--dsw-alias-border-l1': '#3a2e0f0d',
    '--dsw-alias-border-l2': '#3a2e0f1a',
    '--dsw-alias-border-l3': '#3a2e0f24',
    '--dsw-alias-border-l4': '#3a2e0f38',
    '--dsw-alias-border-inverted': '#ffffff1f',
    '--dsw-alias-label-primary': '#3a2e0f',
    '--dsw-alias-label-secondary': '#6b5a2e',
    '--dsw-alias-label-tertiary': '#7d6b3a',
    '--dsw-alias-label-caption': '#95814f',
    '--dsw-alias-label-dimmed': '#dccfa8',
    '--dsw-alias-label-primary-dimmed': '#4d3d16',
    '--dsw-alias-label-primary-foreground': '#ffffff',
    '--dsw-alias-label-primary-inverted': '#ffffff',
    '--dsw-alias-label-primary-bluish': '#3a2e0f',
    '--dsw-alias-brand-primary': '#3a2e0f',
    '--dsw-alias-brand-primary-invert': '#3a2e0f',
    '--dsw-alias-brand-text': '#3a2e0f',
    '--dsw-alias-state-business-primary': '#2f8fc4',
    '--dsw-alias-state-business-tertiary': '#e8f4fb',
    '--dsw-alias-state-success-primary': '#428f5e',
    '--dsw-alias-state-success-secondary': '#8bd0a2',
    '--dsw-alias-state-success-tertiary': '#eaf7ee',
    '--dsw-alias-state-warn-primary': '#b06f18',
    '--dsw-alias-state-warn-secondary': '#e0952f',
    '--dsw-alias-state-warn-tertiary': '#fdf2e2',
    '--dsw-alias-state-error-primary': '#c94a35',
    '--dsw-alias-state-error-secondary': '#e8654f',
    '--dsw-alias-interactive-bg-hover': '#e8a92a17',
    '--dsw-alias-interactive-bg-hover-solid': '#fdf4e2',
    '--dsw-alias-interactive-bg-active': '#e8a92a29',
    '--dsw-alias-interactive-bg-hover-accent': '#e8a92a29',
    '--dsw-alias-interactive-bg-hover-danger': '#e8654f14',
    '--dsw-alias-button-primary-fill': '#e8a92a',
    '--dsw-alias-button-primary-hover': '#d99a1e',
    '--dsw-alias-button-primary-dimmed': '#fae5b5',
    '--dsw-alias-button-info-fill': '#2f8fc4',
    '--dsw-alias-button-info-hover': '#277faf',
    '--dsw-alias-button-elevated-fill': '#ffffff',
    '--dsw-alias-button-floating-fill': '#ffffff',
    '--dsw-alias-button-floating-hover': '#fdf9ee',
    '--dsw-alias-button-contrast-fill': '#3a2e0f',
    '--dsw-alias-button-ghost-active-fill': '#fbf0d8',
    '--dsw-alias-button-ghost-active-border': '#95814f',
    '--dsw-alias-button-ghost-active-hover': '#f7e8c8',
    '--dsw-alias-markdown-code-block': '#fdf7ea',
    '--dsw-alias-markdown-code-block-banner': '#faf0dc',
    '--dsw-alias-markdown-inline-code': '#fbf1dd',
    '--dsw-alias-markdown-tag': '#fbf1dd',
    '--dsw-alias-markdown-citation': '#fbf1dd',
    '--dsw-alias-markdown-placeholder': '#fdf9ee',
    '--dsw-alias-markdown-code-segment-selected': '#ffffff',
    '--dsw-alias-markdown-code-segment-unselected': '#fdf9ee',
    '--dsw-alias-scrollbar-bg-l1': '#e6d9b4',
    '--dsw-alias-scrollbar-bg-l2': '#dccda4',
    '--dsw-alias-scrollbar-hover-l1': '#c9b78a',
    '--dsw-alias-scrollbar-hover-l2': '#c9b78a',
    '--dsw-alias-tooltip-bg': '#3a2e0f',
    '--dsw-alias-toast-bg': '#4d3d16',
    '--dsw-specific-bubble': '#fdf4e2',
    '--dsw-specific-bubble-highlight': '#ffffff',
    '--dsw-specific-input-major': '#ffffff',
    '--dsw-specific-login-input': '#ffffff',
    '--dsw-specific-menu': '#ffffff',
    '--dsw-specific-selector': '#fdf8ec',
    '--dsw-specific-sidebar-fill': '#fdf4df',
    '--dsw-specific-sidebar-nav-item-hover': '#e8a92a17',
    '--dsw-specific-sidebar-nav-item-active': '#fae5b5',
    '--dsw-specific-sidebar-nav-item-active-accent': '#e8a92a',
    '--dsw-specific-tip': '#fbf1dd',
  }),
}

export const lemonCreamDark = {
  id: 'lemon-cream-dark',
  colorScheme: 'dark',
  family: '鏌犳濂舵补',
  accent: '#f5cf6b',
  accentAlt: '#7fc6e8',
  anchorHex: '#f5cf6b',
  tokens: build({
    '--dsw-alias-bg-base': '#1d1a12',
    '--dsw-alias-bg-layer-1': '#26221a',
    '--dsw-alias-bg-layer-2': '#302b21',
    '--dsw-alias-bg-layer-3': '#3a342a',
    '--dsw-alias-bg-overlay': '#463f33',
    '--dsw-alias-bg-module-platform': '#302b21',
    '--dsw-alias-bg-multi-select': '#3a342a',
    '--dsw-alias-bg-skeleton': '#ffffff14',
    '--dsw-alias-bg-mask-1': '#00000080',
    '--dsw-alias-bg-mask-2': '#00000033',
    '--dsw-alias-bg-mask-3': '#0000007a',
    '--dsw-alias-border-l1': '#f5d98a1f',
    '--dsw-alias-border-l2': '#f5d98a2e',
    '--dsw-alias-border-l3': '#f5d98a42',
    '--dsw-alias-border-l4': '#f5d98a5c',
    '--dsw-alias-border-inverted': '#ffffff14',
    '--dsw-alias-label-primary': '#faf1d9',
    '--dsw-alias-label-secondary': '#cfc09a',
    '--dsw-alias-label-tertiary': '#b6a882',
    '--dsw-alias-label-caption': '#9c8f6d',
    '--dsw-alias-label-dimmed': '#57503a',
    '--dsw-alias-label-primary-dimmed': '#e8dcb8',
    '--dsw-alias-label-primary-foreground': '#1d1a12',
    '--dsw-alias-label-primary-inverted': '#26221a',
    '--dsw-alias-label-primary-bluish': '#faf1d9',
    '--dsw-alias-brand-primary': '#faf1d9',
    '--dsw-alias-brand-primary-invert': '#faf1d9',
    '--dsw-alias-brand-text': '#faf1d9',
    '--dsw-alias-state-business-primary': '#7fc6e8',
    '--dsw-alias-state-business-tertiary': '#1f3540',
    '--dsw-alias-state-success-primary': '#8bd6a0',
    '--dsw-alias-state-success-secondary': '#b0e6c0',
    '--dsw-alias-state-success-tertiary': '#22371f',
    '--dsw-alias-state-warn-primary': '#f0b45c',
    '--dsw-alias-state-warn-secondary': '#f7cd8c',
    '--dsw-alias-state-warn-tertiary': '#3d3118',
    '--dsw-alias-state-error-primary': '#f28d7a',
    '--dsw-alias-state-error-secondary': '#ffb3a4',
    '--dsw-alias-interactive-bg-hover': '#f5cf6b1f',
    '--dsw-alias-interactive-bg-hover-solid': '#3a342a',
    '--dsw-alias-interactive-bg-active': '#f5cf6b33',
    '--dsw-alias-interactive-bg-hover-accent': '#f5cf6b3d',
    '--dsw-alias-interactive-bg-hover-danger': '#f28d7a26',
    '--dsw-alias-button-primary-fill': '#f5cf6b',
    '--dsw-alias-button-primary-hover': '#ffe08c',
    '--dsw-alias-button-primary-dimmed': '#5a4c26',
    '--dsw-alias-button-info-fill': '#7fc6e8',
    '--dsw-alias-button-info-hover': '#9ed8f2',
    '--dsw-alias-button-elevated-fill': '#3a342a',
    '--dsw-alias-button-floating-fill': '#302b21',
    '--dsw-alias-button-floating-hover': '#3a342a',
    '--dsw-alias-button-contrast-fill': '#faf1d9',
    '--dsw-alias-button-ghost-active-fill': '#3a342a',
    '--dsw-alias-button-ghost-active-border': '#82764f',
    '--dsw-alias-button-ghost-active-hover': '#5a4c26',
    '--dsw-alias-markdown-code-block': '#211d15',
    '--dsw-alias-markdown-code-block-banner': '#302b21',
    '--dsw-alias-markdown-inline-code': '#3a342a',
    '--dsw-alias-markdown-tag': '#3a342a',
    '--dsw-alias-markdown-citation': '#3a342a',
    '--dsw-alias-markdown-placeholder': '#302b21',
    '--dsw-alias-markdown-code-segment-selected': '#3a342a',
    '--dsw-alias-markdown-code-segment-unselected': '#211d15',
    '--dsw-alias-scrollbar-bg-l1': '#463f33',
    '--dsw-alias-scrollbar-bg-l2': '#57503a',
    '--dsw-alias-scrollbar-hover-l1': '#6b6247',
    '--dsw-alias-scrollbar-hover-l2': '#6b6247',
    '--dsw-alias-tooltip-bg': '#463f33',
    '--dsw-alias-toast-bg': '#5a4c26',
    '--dsw-specific-bubble': '#3a342a',
    '--dsw-specific-bubble-highlight': '#302b21',
    '--dsw-specific-input-major': '#302b21',
    '--dsw-specific-login-input': '#302b21',
    '--dsw-specific-menu': '#3a342a',
    '--dsw-specific-selector': '#302b21',
    '--dsw-specific-sidebar-fill': '#191611',
    '--dsw-specific-sidebar-nav-item-hover': '#f5cf6b1f',
    '--dsw-specific-sidebar-nav-item-active': '#3a342a',
    '--dsw-specific-sidebar-nav-item-active-accent': '#f5cf6b',
    '--dsw-specific-tip': '#3a342a',
  }),
}

export const THEMES = [
  mintSodaLight, mintSodaDark,
  sakuraMochiLight, sakuraMochiDark,
  lemonCreamLight, lemonCreamDark,
]

